apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: ecommerce-monorepo
build:
  artifacts:
    - image: ecommerce-monorepo-cart-service
      context: .
      docker:
        dockerfile: apps/cart/Dockerfile
      sync:
        manual:
          - src: "apps/cart/src/**/*.ts"
            dest: .

    - image: ecommerce-monorepo-catalog-service
      context: .
      docker:
        dockerfile: apps/catalog/Dockerfile
      sync:
        manual:
          - src: "apps/catalog/src/**/*.ts"
            dest: .

    - image: ecommerce-monorepo-api-gateway-service
      context: .
      docker:
        dockerfile: apps/api-gateway/Dockerfile
      sync:
        manual:
          - src: "apps/api-gateway/src/**/*.ts"
            dest: .

    # --- Identity Service ---
    - image: ecommerce-monorepo-identity-service
      context: .
      docker:
        dockerfile: apps/identity/Dockerfile
      sync:
        manual:
          - src: "apps/identity/src/**/*.ts"
            dest: .

    # --- Orders Service ---
    - image: ecommerce-monorepo-orders-service
      context: .
      docker:
        dockerfile: apps/orders/Dockerfile
      sync:
        manual:
          - src: "apps/orders/src/**/*.ts"
            dest: .

    # --- Email Service ---
    - image: ecommerce-monorepo-email-service
      context: .
      docker:
        dockerfile: apps/email/Dockerfile
      sync:
        manual:
          - src: "apps/email/src/**/*.ts"
            dest: .

    # --- Invoice Service ---
    - image: ecommerce-monorepo-invoice-service
      context: .
      docker:
        dockerfile: apps/invoice/Dockerfile
      sync:
        manual:
          - src: "apps/invoice/src/**/*.ts"
            dest: .

deploy:
  kubectl:
    manifests:
      - infra/k8s/*
